# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: producer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'producer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducer.proto\x12\x08producer\"1\n\x12SendMessageRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"W\n\x13SendMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x11\n\tpartition\x18\x03 \x01(\x05\x12\x0e\n\x06offset\x18\x04 \x01(\x03\x32V\n\x08Producer\x12J\n\x0bSendMessage\x12\x1c.producer.SendMessageRequest\x1a\x1d.producer.SendMessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'producer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMESSAGEREQUEST']._serialized_start=28
  _globals['_SENDMESSAGEREQUEST']._serialized_end=77
  _globals['_SENDMESSAGERESPONSE']._serialized_start=79
  _globals['_SENDMESSAGERESPONSE']._serialized_end=166
  _globals['_PRODUCER']._serialized_start=168
  _globals['_PRODUCER']._serialized_end=254
# @@protoc_insertion_point(module_scope)
