apiVersion: apps/v1
kind: Deployment
metadata:
    name: gateway
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gateway
    template:
        metadata:
            labels:
                app: gateway
        spec:
            containers:
                - name: gateway
                  image: matiaspaavilainen/distributed-systems:gateway
                  imagePullPolicy: Always
                  env:
                      - name: PYTHONPATH
                        value: "/app:/app/kafka_messaging/consumer"

                - name: kafka-services
                  image: matiaspaavilainen/distributed-systems:kafka_services
                  imagePullPolicy: Always
                  env:
                      - name: PORT_BASE
                        value: "30050"
                      - name: PYTHONPATH
                        value: "/app/consumer:/app/producer"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: gateway-ingress
    namespace: default
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    ingressClassName: nginx
    rules:
        - http:
              paths:
                  - path: /(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: gateway
                            port:
                                number: 40404
---
apiVersion: v1
kind: Service
metadata:
    name: gateway
    namespace: default
spec:
    selector:
        app: gateway
    ports:
        - protocol: TCP
          port: 40404
          targetPort: 40404
    type: ClusterIP
