apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: kafka
spec:
    serviceName: kafka
    replicas: 4  # One set per VM (control + 3 workers)
    selector:
        matchLabels:
            app: kafka
    template:
        metadata:
            labels:
                app: kafka
        spec:
            # Updated affinity to keep brokers on same node as lookup service
            affinity:
                podAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                        - key: app
                          operator: In
                          values:
                          - lookup
                      topologyKey: kubernetes.io/hostname
            containers:
                - name: kafka
                  image: bitnami/kafka:latest
                  ports:
                      - containerPort: 9092
                  env:
                      - name: KAFKA_CFG_ZOOKEEPER_CONNECT
                        value: zookeeper:2181
                      - name: ALLOW_PLAINTEXT_LISTENER
                        value: "yes"
                      - name: KAFKA_CFG_LISTENERS
                        value: PLAINTEXT://:9092
                      - name: KAFKA_CFG_ADVERTISED_LISTENERS
                        value: PLAINTEXT://$(POD_NAME).kafka:9092
                      # Local replication settings
                      - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
                        value: "1"  # No cross-VM replication
                      - name: KAFKA_CFG_MIN_INSYNC_REPLICAS
                        value: "1"
                      - name: KAFKA_CFG_NUM_PARTITIONS
                        value: "1"
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
    name: kafka
spec:
    clusterIP: None  # Headless service
    selector:
        app: kafka
    ports:
        - protocol: TCP
          port: 9092
          targetPort: 9092