apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-finder
data:
  script: |
    KAFKA_POD=$(kubectl get pods -l app=kafka --field-selector spec.nodeName=${NODE_NAME} --no-headers -o custom-columns=":metadata.name")
    if [ -z "$KAFKA_POD" ]; then
      printf "kafka-0.kafka:9092"
    else
      printf "$KAFKA_POD.kafka:9092"
    fi