apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: kafka-worker
    labels:
        app: kafka
        role: worker
spec:
    serviceName: kafka
    replicas: 3 # One for each worker node
    selector:
        matchLabels:
            app: kafka
            role: worker
    template:
        metadata:
            labels:
                app: kafka
                role: worker
        spec:
            hostNetwork: true
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/worker
                                    operator: Exists
            containers:
                - name: kafka
                  image: bitnami/kafka:latest
                  ports:
                      - containerPort: 9092
                  env:
                      - name: KAFKA_CFG_ZOOKEEPER_CONNECT
                        value: "zookeeper.default.svc.cluster.local:2181" # Use full DNS name
                      - name: ALLOW_PLAINTEXT_LISTENER
                        value: "yes"
                      - name: KAFKA_CFG_LISTENERS
                        value: PLAINTEXT://0.0.0.0:9092
                      - name: KAFKA_CFG_ADVERTISED_LISTENERS
                        value: PLAINTEXT://localhost:9092
---
apiVersion: apps/v1
kind: Deployment # Use Deployment for control plane Kafka
metadata:
    name: kafka-control
    labels:
        app: kafka
        role: control
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka
            role: control
    template:
        metadata:
            labels:
                app: kafka
                role: control
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/control-plane
                                    operator: Exists
            containers:
                - name: kafka
                  image: bitnami/kafka:latest
                  ports:
                      - containerPort: 9092
                  env:
                      - name: KAFKA_CFG_ZOOKEEPER_CONNECT
                        value: "localhost:2181" # Connect to local Zookeeper on control plane
                      - name: ALLOW_PLAINTEXT_LISTENER
                        value: "yes"
                      - name: KAFKA_CFG_LISTENERS
                        value: PLAINTEXT://0.0.0.0:9092
                      - name: KAFKA_CFG_ADVERTISED_LISTENERS
                        value: PLAINTEXT://localhost:9092
---
apiVersion: v1
kind: Service
metadata:
    name: kafka
spec:
    clusterIP: None
    selector:
        app: kafka
    ports:
        - protocol: TCP
          port: 9092
          targetPort: 9092
