apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: kafka
spec:
    serviceName: kafka
    replicas: 3 # One for each worker node
    selector:
        matchLabels:
            app: kafka
    template:
        metadata:
            labels:
                app: kafka
        spec:
            hostNetwork: true # Use host networking
            containers:
                - name: kafka
                  image: bitnami/kafka:latest
                  ports:
                      - containerPort: 9092
                  env:
                      - name: KAFKA_CFG_ZOOKEEPER_CONNECT
                        value: zookeeper:2181
                      - name: ALLOW_PLAINTEXT_LISTENER
                        value: "yes"
                      - name: KAFKA_CFG_LISTENERS
                        value: PLAINTEXT://0.0.0.0:9092
                      - name: KAFKA_CFG_ADVERTISED_LISTENERS
                        value: PLAINTEXT://localhost:9092 # Changed to localhost
---
apiVersion: v1
kind: Service
metadata:
    name: kafka
spec:
    clusterIP: None # Headless service
    selector:
        app: kafka
    ports:
        - protocol: TCP
          port: 9092
          targetPort: 9092
