apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-finder
data:
  script: |
    #!/bin/sh
    KAFKA_POD=$(kubectl get pods -l app=kafka -o wide | grep ${NODE_NAME} | awk '{print $1}')
    echo "${KAFKA_POD}.kafka:9092"