apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: kafka
spec:
    serviceName: kafka
    replicas: 4
    selector:
        matchLabels:
            app: kafka
    template:
        metadata:
            labels:
                app: kafka
        spec:
            affinity:
                podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 100
                      podAffinityTerm:
                        labelSelector:
                            matchExpressions:
                            - key: app
                              operator: In
                              values:
                              - kafka
                        topologyKey: kubernetes.io/hostname
            containers:
                - name: kafka
                  image: bitnami/kafka:latest
                  ports:
                      - containerPort: 9092
                  env:
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: KAFKA_CFG_ZOOKEEPER_CONNECT
                        value: "zookeeper:2181"
                      - name: ALLOW_PLAINTEXT_LISTENER
                        value: "yes"
                      - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
                        value: "INTERNAL:PLAINTEXT"
                      - name: KAFKA_CFG_LISTENERS
                        value: "INTERNAL://:9092"
                      - name: KAFKA_CFG_ADVERTISED_LISTENERS
                        value: "INTERNAL://$(POD_NAME).kafka:9092"
                      - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
                        value: "INTERNAL"
                      - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
                        value: "1"
                      - name: KAFKA_CFG_MIN_INSYNC_REPLICAS
                        value: "1"
                      - name: KAFKA_CFG_NUM_PARTITIONS
                        value: "1"