apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: lookup
spec:
    serviceName: lookup
    replicas: 4
    selector:
        matchLabels:
            app: lookup
    template:
        metadata:
            labels:
                app: lookup
        spec:
            hostNetwork: true # Add host networking
            containers:
                - name: lookup
                  image: matiaspaavilainen/distributed-systems:lookup_service
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 50051
                  env:
                      - name: MONGO_URL
                        value: "mongodb://root:example@localhost:27017" # Changed to localhost
                      - name: PYTHONPATH
                        value: "/app:/app/kafka_messaging/consumer:/app/kafka_messaging/producer:/app/grpc_sharing"
                - name: kafka-services
                  image: matiaspaavilainen/distributed-systems:kafka_services
                  imagePullPolicy: Always
                  env:
                      - name: PORT_BASE
                        value: "30000"
                      - name: PYTHONPATH
                        value: "/app/consumer:/app/producer"
