apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: lookup
spec:
    serviceName: lookup
    replicas: 4 # Match Kafka and MongoDB replicas
    selector:
        matchLabels:
            app: lookup
    template:
        metadata:
            labels:
                app: lookup
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/control-plane
                                    operator: Exists
                                  - key: kafka-ordinal
                                    operator: In
                                    values:
                                        - "0" # Match control-plane with kafka-0
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/worker
                                    operator: Exists
                                  - key: kafka-ordinal
                                    operator: In
                                    values:
                                        - "1" # Match workers with kafka-1,2,3
                                        - "2"
                                        - "3"
            containers:
                - name: lookup
                  image: matiaspaavilainen/distributed-systems:lookup_service
                  imagePullPolicy: Always
                  env:
                      - name: ORDINAL
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: MONGO_URL
                        value: "mongodb-${ORDINAL##*-}.mongodb:27017"
                - name: kafka-services
                  image: matiaspaavilainen/distributed-systems:kafka_services
                  imagePullPolicy: Always
                  env:
                      - name: ORDINAL
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: KAFKA_BROKER
                        value: "kafka-${ORDINAL##*-}.kafka:9092"
