---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-main
  labels:
    app: mongodb
    role: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      role: main
  template:
    metadata:
      labels:
        app: mongodb
        role: main
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "example"
          volumeMounts:
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-init
          configMap:
            name: mongo-init-script
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-node
  labels:
    app: mongodb
    role: node
spec:
  serviceName: mongodb-node
  replicas: 3  # One per worker node
  selector:
    matchLabels:
      app: mongodb
      role: node
  template:
    metadata:
      labels:
        app: mongodb
        role: node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "example"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-main-service
spec:
  selector:
    app: mongodb
    role: main
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-node-service
spec:
  selector:
    app: mongodb
    role: node
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017