---
apiVersion: apps/v1
kind: StatefulSet # Changed to StatefulSet for consistent ordinal-based naming
metadata:
    name: mongodb
    labels:
        app: mongodb
spec:
    serviceName: mongodb
    replicas: 4 # 3 workers + 1 control plane, matching Kafka
    selector:
        matchLabels:
            app: mongodb
    template:
        metadata:
            labels:
                app: mongodb
        spec:
            initContainers:
                - name: node-labeler
                  image: bitnami/kubectl
                  command:
                      - /bin/sh
                      - -c
                      - |
                          NODE=$(kubectl get pod ${POD_NAME} -o=jsonpath='{.spec.nodeName}')
                          kubectl label node $NODE mongodb-ordinal=${ORDINAL} --overwrite
                  env:
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: ORDINAL
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.annotations['statefulset.kubernetes.io/pod-name']
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: kafka-ordinal
                                    operator: In
                                    values:
                                        - kafka-$(ORDINAL) # Match with corresponding Kafka broker
            containers:
                - name: mongodb
                  image: mongo:latest
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        value: "root"
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        value: "example"
                      - name: ORDINAL
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.annotations['statefulset.kubernetes.io/pod-name']
---
apiVersion: v1
kind: Service
metadata:
    name: mongodb
spec:
    clusterIP: None # Headless service for StatefulSet DNS
    selector:
        app: mongodb
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
