apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: proxy-node-monitor
    namespace: monitoring
    labels:
        release: prometheus # Match the helm release name
spec:
    namespaceSelector:
        matchNames:
            - default
    selector:
        matchLabels:
            app: proxy-node
    endpoints:
        - port: http
          path: /metrics
          interval: 15s
