apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: ingress-controller-monitor
    namespace: monitoring
    labels:
        release: prometheus
spec:
    namespaceSelector:
        matchNames:
            - ingress-nginx
    selector:
        matchLabels:
            app.kubernetes.io/name: ingress-nginx
            app.kubernetes.io/component: controller
    endpoints:
        - port: metrics
          interval: 15s
          scheme: http
          path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: server-metrics
    namespace: monitoring
spec:
    selector:
        matchLabels:
            app: control
    endpoints:
        - port: metrics
          interval: 15s
          path: /metrics
    namespaceSelector:
        matchNames:
            - default
