apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: proxy-node-monitor
    # This should match the namespace where your Prometheus operator is installed
    namespace: monitoring
    labels:
        # These labels should match the Prometheus instance's serviceMonitorSelector
        release: prometheus
spec:
    selector:
        matchLabels:
            app: proxy-node
    endpoints:
        - port: http
          path: /metrics
          interval: 15s
