apiVersion: v1
kind: Service
metadata:
    name: prometheus-public
    namespace: monitoring
spec:
    type: NodePort
    ports:
        - port: 9090
          targetPort: 9090
          nodePort: 30909
          name: http
    selector:
        prometheus: prometheus-kube-prometheus-prometheus
