apiVersion: v1
kind: Service
metadata:
    name: proxy-nodes
spec:
    type: NodePort
    selector:
        app: proxy-node
    ports:
        - name: http
          port: 80
          targetPort: http # Reference port by name instead of number
          nodePort: 30080
