apiVersion: apps/v1
kind: Deployment
metadata:
    name: server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            containers:
                - name: server
                  image: matiaspaavilainen/distributed-systems:main_server
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 40002
                  env:
                      - name: MONGO_URL
                        value: "mongodb://root:example@mongodb-service:27017"
---
apiVersion: v1
kind: Service
metadata:
    name: server-service
spec:
    selector:
        app: server
    ports:
        - protocol: TCP
          port: 40002
          targetPort: 40002
    type: ClusterIP
    # ClusterIP makes it only accesible inside the cluster, maybe need to change later
