apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: worker
    labels:
        app: worker
spec:
    serviceName: worker
    replicas: 3
    selector:
        matchLabels:
            app: worker
    template:
        metadata:
            labels:
                app: worker
        spec:
            serviceAccountName: node-manager-account
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/worker
                                    operator: Exists
                # one per worker node
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        - labelSelector:
                              matchLabels:
                                  app: worker
                          topologyKey: "kubernetes.io/hostname"

            containers:
                # ZOOKEEPER
                - name: zookeeper
                  image: bitnami/zookeeper:latest
                  ports:
                      - containerPort: 2181
                  readinessProbe:
                      tcpSocket:
                          port: 2181
                      initialDelaySeconds: 15
                      periodSeconds: 5
                  env:
                      - name: ALLOW_ANONYMOUS_LOGIN
                        value: "yes"
                      - name: ZOO_STANDALONE_ENABLED
                        value: "yes"
                      - name: ZOO_MAX_CLIENT_CNXNS
                        value: "2"
                      - name: ZOO_4LW_COMMANDS_WHITELIST
                        value: "srvr,ruok,stat,mntr"
                # KAFKA
                - name: kafka
                  image: bitnami/kafka:latest
                  ports:
                      - containerPort: 9092
                  readinessProbe:
                      tcpSocket:
                          port: 9092
                      initialDelaySeconds: 20
                      periodSeconds: 5
                  env:
                      - name: KAFKA_CFG_ZOOKEEPER_CONNECT
                        value: "localhost:2181" # Zookeeper within the same pod
                      - name: KAFKA_CFG_BROKER_ID
                        value: "1" # Static for simplicity
                      - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
                        value: "PLAINTEXT:PLAINTEXT"
                      - name: ALLOW_PLAINTEXT_LISTENER
                        value: "yes"
                      - name: POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: KAFKA_CFG_LISTENERS
                        value: "PLAINTEXT://0.0.0.0:9092"
                      - name: KAFKA_CFG_ADVERTISED_LISTENERS
                        value: "PLAINTEXT://$(POD_IP):9092"
                # MONGODB
                - name: mongodb
                  image: mongo:latest
                  ports:
                      - containerPort: 27017
                  readinessProbe:
                      tcpSocket:
                          port: 27017
                      initialDelaySeconds: 15
                      periodSeconds: 5
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        value: "root"
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        value: "example"
                # LOOKUP
                - name: lookup
                  image: matiaspaavilainen/distributed-systems:lookup_service
                  imagePullPolicy: Always
                  readinessProbe:
                      tcpSocket:
                          port: 50051
                      initialDelaySeconds: 25 # Wait for kafka
                      periodSeconds: 5
                  env:
                      - name: PYTHONPATH
                        value: "/app:/app/kafka_messaging/consumer:/app/kafka_messaging/producer:/app/grpc_sharing/"
                      - name: KAFKA_SERVICE_PORT
                        value: "2050"

                - name: lookup-kafka-services
                  image: matiaspaavilainen/distributed-systems:kafka_services
                  imagePullPolicy: Always
                  env:
                      - name: PYTHONPATH
                        value: "/app/consumer:/app/producer"
                      - name: PORT_BASE
                        value: "2050"
                # NODE MANAGER
                - name: node-manager
                  image: matiaspaavilainen/distributed-systems:node_manager
                  imagePullPolicy: Always
                  command: [
                          "sh",
                          "-c",
                          '
                          echo "Waiting for all worker pods to be ready...";
                          until wget -T 2 -q -O - http://worker-0.worker:50051 >/dev/null 2>&1 &&
                          wget -T 2 -q -O - http://worker-1.worker:50051 >/dev/null 2>&1 &&
                          wget -T 2 -q -O - http://worker-2.worker:50051 >/dev/null 2>&1; do
                          echo "Waiting for all worker lookup services...";
                          sleep 5;
                          done;
                          echo "All worker lookup services ready! Starting node-manager...";
                          # Launch the actual node-manager process
                          exec python /app/main.py
                          ',
                      ]
                  readinessProbe:
                      tcpSocket:
                          port: 50051
                      initialDelaySeconds: 15
                      periodSeconds: 5
                  env:
                      - name: POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name

---
# Need to be hardcoded
apiVersion: v1
kind: Service
metadata:
    name: worker-0
spec:
    selector:
        app: worker
        statefulset.kubernetes.io/pod-name: worker-0
    ports:
        - name: kafka
          protocol: TCP
          port: 9092
          targetPort: 9092
        - name: mongodb
          protocol: TCP
          port: 27017
          targetPort: 27017
        - name: lookup
          protocol: TCP
          port: 50051
          targetPort: 50051
    type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
    name: worker-1
spec:
    selector:
        app: worker
        statefulset.kubernetes.io/pod-name: worker-1
    ports:
        - name: kafka
          protocol: TCP
          port: 9092
          targetPort: 9092
        - name: mongodb
          protocol: TCP
          port: 27017
          targetPort: 27017
        - name: lookup
          protocol: TCP
          port: 50051
          targetPort: 50051
    type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
    name: worker-2
spec:
    selector:
        app: worker
        statefulset.kubernetes.io/pod-name: worker-2
    ports:
        - name: kafka
          protocol: TCP
          port: 9092
          targetPort: 9092
        - name: mongodb
          protocol: TCP
          port: 27017
          targetPort: 27017
        - name: lookup
          protocol: TCP
          port: 50051
          targetPort: 50051
    type: ClusterIP
