{
 "title": "Basic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ingress RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_requests_total[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Main Server RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_requests_total{status=\"received\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Proxy CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"proxy-node.*\"}[1m])) / sum(machine_cpu_cores) * 100",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Main Server latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(grpc_server_request_duration_seconds_sum[1m]) / rate(grpc_server_request_duration_seconds_count[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}