# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/data.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/data.proto\x12\x04SAND\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0cRequestReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2D\n\x0eRequestService\x12\x32\n\x0bRequestData\x12\r.SAND.Request\x1a\x12.SAND.RequestReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=27
  _globals['_REQUEST']._serialized_end=50
  _globals['_REQUESTREPLY']._serialized_start=52
  _globals['_REQUESTREPLY']._serialized_end=80
  _globals['_REQUESTSERVICE']._serialized_start=82
  _globals['_REQUESTSERVICE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
