# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import consumer_pb2 as consumer__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in consumer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsumerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestMessage = channel.unary_unary(
                '/consumer.Consumer/GetLatestMessage',
                request_serializer=consumer__pb2.GetLatestMessageRequest.SerializeToString,
                response_deserializer=consumer__pb2.GetLatestMessageResponse.FromString,
                _registered_method=True)
        self.ListenForNewMessages = channel.unary_stream(
                '/consumer.Consumer/ListenForNewMessages',
                request_serializer=consumer__pb2.ListenForNewMessagesRequest.SerializeToString,
                response_deserializer=consumer__pb2.ListenForNewMessagesResponse.FromString,
                _registered_method=True)


class ConsumerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLatestMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenForNewMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsumerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestMessage,
                    request_deserializer=consumer__pb2.GetLatestMessageRequest.FromString,
                    response_serializer=consumer__pb2.GetLatestMessageResponse.SerializeToString,
            ),
            'ListenForNewMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenForNewMessages,
                    request_deserializer=consumer__pb2.ListenForNewMessagesRequest.FromString,
                    response_serializer=consumer__pb2.ListenForNewMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'consumer.Consumer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('consumer.Consumer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Consumer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLatestMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consumer.Consumer/GetLatestMessage',
            consumer__pb2.GetLatestMessageRequest.SerializeToString,
            consumer__pb2.GetLatestMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenForNewMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/consumer.Consumer/ListenForNewMessages',
            consumer__pb2.ListenForNewMessagesRequest.SerializeToString,
            consumer__pb2.ListenForNewMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
