# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lookup_sharing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'lookup_sharing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14lookup_sharing.proto\x12\x0elookup_sharing\"A\n\rUpdateRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x14\n\x0cvector_clock\x18\x03 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"5\n\x12LookupTableRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\"Q\n\x13LookupTableResponse\x12\x12\n\ntable_data\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xbe\x01\n\rLookupSharing\x12R\n\x11ReceivePeerUpdate\x12\x1d.lookup_sharing.UpdateRequest\x1a\x1e.lookup_sharing.UpdateResponse\x12Y\n\x0eGetLookupTable\x12\".lookup_sharing.LookupTableRequest\x1a#.lookup_sharing.LookupTableResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lookup_sharing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEREQUEST']._serialized_start=40
  _globals['_UPDATEREQUEST']._serialized_end=105
  _globals['_UPDATERESPONSE']._serialized_start=107
  _globals['_UPDATERESPONSE']._serialized_end=140
  _globals['_LOOKUPTABLEREQUEST']._serialized_start=142
  _globals['_LOOKUPTABLEREQUEST']._serialized_end=195
  _globals['_LOOKUPTABLERESPONSE']._serialized_start=197
  _globals['_LOOKUPTABLERESPONSE']._serialized_end=278
  _globals['_LOOKUPSHARING']._serialized_start=281
  _globals['_LOOKUPSHARING']._serialized_end=471
# @@protoc_insertion_point(module_scope)
